version: '3.7'
services:
  flask-app:
    image: "jnoori31/qa-flask-app:${TAG}"
    build: .
    depends_on:
      - mysql-db
    deploy:
      replicas: 1
    ports:
    - published: 5000
      target: 5000
    environment:
      DATABASE_URI: "mysql+pymysql://${DB_USER}:${DB_PASSWORD}@mysql-db:3306/qa_db"
  
  mysql-db:
    image: mysql:5.7
    deploy:
      replicas: 1
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_DATABASE: 'qa_db'
    ports:
    - published: 3306
      target: 3306
    volumes:
      - database-data:/var/lib/mysql

  nginx:
    image: nginx:latest
    deploy:
      replicas: 1
    ports:
      - published: 80
        target: 80
    configs:
      - source: nginx_config
        target: /etc/nginx/nginx.conf

configs:
  nginx_config:
    file: ./nginx.conf

volumes:
  database-data:
    