pipeline {
    agent any
    environment {
        DOCKER_LOGIN = credentials('DOCKER_LOGIN')
    }
    stages {
        stage('Setup') {
            steps {
                sh "bash jenkins/setup.sh"
            }
        }
        stage('Test') {
            steps {
                sh "bash jenkins/test.sh"
            }
        }
        stage('Build') {
            steps {
                sh "echo test"
            }
        }
        stage('Push') {
            steps {
                sh "echo test"
            }
        }
        stage('Deploy') {
            steps {
                sh "echo test"
            }
        }
    }
}
