pipeline {
    agent any
    environment {
        DOCKER_LOGIN = credentials('DOCKER_LOGIN')
        DB_LOGIN = credentials('db-secret')
        DB_ROOT = credentials('db-root')
    }
    stages {
        stage('Setup') {
            steps {
                sh "env"
                sh "bash jenkins/setup.sh"
            }
        }
        stage('Test') {
            steps {
                sh "bash jenkins/test.sh"
            }
        }
        stage('Build') {
            steps {
                // running inline as it is only one command
                sh "docker-compose -f docker-stack.yml build"
            }
        }
        stage('Push') {
            steps {
                // running inline as it is only one command
                sh "docker-compose -f docker-stack.yml push"
            }
        }
        stage('Deploy') {
            steps {
                sh "bash jenkins/deploy.sh"
            }
        }
    }
}
